AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Stage:
    Type: String
    AllowedValues:
      - dev
      - prodblue
      - prodgreen
Resources:
  ContainerRepository:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName:
        Fn::Sub: "sportnumerics-stats-${Stage}"
  TeamsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: year
          AttributeType: S
        - AttributeName: div
          AttributeType: S
      KeySchema:
        - AttributeName: year
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: by_div
          KeySchema:
            - AttributeName: year
              KeyType: HASH
            - AttributeName: div
              KeyType: RANGE
          Projection:
            NonKeyAttributes:
              - name
              - schedule
              - ratings
            ProjectionType: INCLUDE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 20
  DivisionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: year
          AttributeType: S
      KeySchema:
        - AttributeName: year
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
Outputs:
  DivsTableName:
    Description: Divs table name in DynamoDB
    Value:
      Ref: DivisionsTable
  TeamsTableName:
    Description: Teams table name in DynamoDB
    Value:
      Ref: TeamsTable
