AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TeamsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: year
          AttributeType: S
        - AttributeName: div
          AttributeType: S
      KeySchema:
        - AttributeName: year
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: by_div
          KeySchema:
            - AttributeName: year
              KeyType: HASH
            - AttributeName: div
              KeyType: RANGE
          Projection:
            NonKeyAttributes:
              - name
              - schedule
              - ratings
            ProjectionType: INCLUDE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 20
  DivisionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: year
          AttributeType: S
      KeySchema:
        - AttributeName: year
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
Outputs:
  DivsTableName:
    Description: Divs table name in DynamoDB
    Value:
      Ref: DivisionsTable
  TeamsTableName:
    Description: Teams table name in DynamoDB
    Value:
      Ref: TeamsTable
