AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Stage:
    Type: String
    AllowedValues:
      - dev
      - prodblue
      - prodgreen
Resources:
  ContainerRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName:
        Fn::Sub: "sportnumerics-stats-${Stage}"
  Cluster:
    Type: AWS::ECS::Cluster
  Task:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
      - Name: stats
        Image:
          Fn::Sub: "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/sportnumerics-stats-${Stage}:latest"
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group:
              Ref: EcsLogs
            awslogs-region:
              Ref: AWS::Region
            awslogs-stream-prefix:
              Fn::Sub: "stats-${Stage}"
        Environment:
        - Name: RESULTS_TABLE
          Value:
            Ref: TeamsTable
        - Name: DIVISIONS_TABLE
          Value:
            Ref: DivisionsTable
        - Name: STAGE
          Value:
            Ref: Stage
        - Name: AWS_DEFAULT_REGION
          Value:
            Ref: AWS::Region
        - Name: PREDICT_LAMBDA_ARN
          Value:
            Fn::Sub: "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:sportnumerics-predict-${Stage}-predict"
      Memory: 1GB
      Cpu: 256
      RequiresCompatibilities:
        - FARGATE
      TaskRoleArn:
        Ref: TaskRole
      ExecutionRoleArn:
        Ref: TaskExecutionRole
      NetworkMode: awsvpc
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: TaskExecutionRole
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'ecr:GetAuthorizationToken'
                  - 'ecr:BatchCheckLayerAvailability'
                  - 'ecr:GetDownloadUrlForLayer'
                  - 'ecr:BatchGetImage'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: TaskRole
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:UpdateItem'
                  - 'dynamodb:Query'
                Resource:
                  - Fn::GetAtt: [TeamsTable, Arn]
                  - Fn::GetAtt: [DivisionsTable, Arn]
              - Effect: Allow
                Action: 'lambda:InvokeFunction'
                Resource: 
                  Fn::Sub: "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:sportnumerics-predict-${Stage}-predict"
  TaskEventRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: rate(1 hour)
      Targets:
        - Id: EcsTarget
          Arn:
            Fn::GetAtt: [Cluster, Arn]
          EcsParameters:
            TaskCount: 1
            TaskDefinitionArn:
              Ref: Task
          RoleArn:
            Fn::GetAtt: [TaskEventRuleRole, Arn]
  TaskEventRuleRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: TaskEventRuleRole
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'ecs:RunTask'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'iam:PassRole'
                Resource:
                  - Fn::GetAtt: [TaskExecutionRole, Arn]
  EcsLogs:
    Type: AWS::Logs::LogGroup
  TeamsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: year
          AttributeType: S
        - AttributeName: div
          AttributeType: S
      KeySchema:
        - AttributeName: year
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: by_div
          KeySchema:
            - AttributeName: year
              KeyType: HASH
            - AttributeName: div
              KeyType: RANGE
          Projection:
            NonKeyAttributes:
              - name
              - schedule
              - ratings
            ProjectionType: INCLUDE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 20
  DivisionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: year
          AttributeType: S
      KeySchema:
        - AttributeName: year
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
Outputs:
  DivsTableName:
    Description: Divs table name in DynamoDB
    Value:
      Ref: DivisionsTable
  TeamsTableName:
    Description: Teams table name in DynamoDB
    Value:
      Ref: TeamsTable
