FROM node:alpine

WORKDIR /work

RUN apk add --no-cache bash curl git docker py-pip openssl

RUN pip install --upgrade pip

RUN pip install --upgrade awscli

ADD package.json yarn.lock .

RUN yarn

ADD . .

RUN yarn test

CMD ./deploy.sh
