FROM node:8-alpine

WORKDIR /work

RUN apk add --no-cache bash curl git docker py-pip openssl

RUN pip install --upgrade pip

RUN pip install --upgrade awscli

ADD package.json .

RUN npm install

ADD . .

RUN npm test

CMD ./deploy.sh
