Resources:
  TeamsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: season
          AttributeType: S
        - AttributeName: div
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: season
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: schedule
          KeySchema:
            - AttributeName: season
              KeyType: HASH
            - AttributeName: div
              KeyType: RANGE
          Projection:
            NonKeyAttributes:
              - team
              - schedule
            ProjectionType: INCLUDE
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 10
      TableName: ${file(serverless.yml):custom.teamsTableName}
  DivisionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: season
          AttributeType: S
      KeySchema:
        - AttributeName: season
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: ${file(serverless.yml):custom.divisionsTableName}
