service: sportnumerics-stats
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-southeast-2
  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "s3:ListBucket"
    Resource: ${self:custom.resultsBucketArn}
  - Effect: "Allow"
    Action:
      - "s3:PutObject"
    Resource: "${self:custom.resultsBucketArn}/*"
  - Effect: "Allow"
    Action:
      - "lambda:InvokeFunction"
    Resource: ${self:custom.predictLambdaArn}
  environment:
    PREDICT_LAMBDA_ARN: ${self:custom.predictLambdaArn}
    RESULTS_BUCKET: ${self:custom.resultsBucketName}
    RESULTS_TABLE: ${self:custom.teamsTableName}
    DIVISIONS_TABLE: ${self:custom.divisionsTableName}
package:
  exclude:
  - config/env.sh
custom:
  resultsBucketName: sportnumerics-stats-${opt:stage}
  resultsBucketArn: "arn:aws:s3:::${self:custom.resultsBucketName}"
  teamsTableName: sportnumerics-stats-teams-${opt:stage}
  divisionsTableName: sportnumerics-stats-divs-${opt:stage}
  predictLambdaArn:
    Fn::Join:
    - ":"
    - - "arn:aws:lambda"
      - Ref: AWS::Region
      - Ref: AWS::AccountId
      - "function"
      - "sportnumerics-predict-${opt:stage}-predict"

resources: ${file(resources.yml)}

functions:
  collectAll:
    handler: handler.collectAll
    timeout: 300
    events:
    - schedule: rate(24 hours)
