service: sportnumerics-stats
provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: ap-southeast-2
  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "s3:ListBucket"
    Resource: "arn:aws:s3:::sportnumerics-stats-${opt:stage}"
  - Effect: "Allow"
    Action:
      - "s3:PutObject"
    Resource: "arn:aws:s3:::sportnumerics-stats-${opt:stage}/*"
  - Effect: "Allow"
    Action:
      - "SNS:Publish"
    Resource: ${self:custom.snsTopicArn}
  environment:
    SNS_TOPIC: ${self:custom.snsTopicArn}
package:
  exclude:
  - config/env.sh
custom:
  snsTopicName: sportnumerics-stats-${opt:stage}
  snsTopicArn:
    Fn::Join:
      - ':'
      - - 'arn:aws:sns'
        - Ref: AWS::Region
        - Ref: AWS::AccountId
        - ${self:custom.snsTopicName}

functions:
  initiate:
    handler: handler.initiate
    events:
    - schedule:
      rate: rate(24 hours)
      enabled: false
  collect:
    handler: handler.collect
    timeout: 200
    events:
    - sns:
        topicName: ${self:custom.snsTopicName}
        displayName: "Stats Collection Routing"
