service: sportnumerics
provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: ap-southeast-2
package:
  exclude:
  - config/env.sh

functions:
  teamsCollect:
    handler: teams.collect
    events:
    - schedule: rate(2 hours)
