service: sportnumerics
provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: ap-southeast-2
  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "s3:ListBucket"
    Resource: "arn:aws:s3:::sportnumerics-stats-${opt:stage}"
  - Effect: "Allow"
    Action:
      - "s3:PutObject"
    Resource: "arn:aws:s3:::sportnumerics-stats-${opt:stage}/*"
package:
  exclude:
  - config/env.sh

functions:
  teamsCollect:
    handler: teams.collect
    events:
    - schedule: rate(24 hours)
